(in-package :elm-app)

(defun on-new-essential-page (body)
  (setf (title (html-document body)) "Essential | ELM")
  (let* ((nav (create-navbar body))
         (bread (create-breadcrumb body))
         (br (create-section body :br))
         (box (create-div (create-div body :class "container") :class "columns")))
    (create-menu-list box :class "column is-one-quarter")
    (create-div box :class "column" :content "contetn")
    (create-menu-list box :class "column is-one-fifth")
    (create-footer body)))
